[build]
  functions="my_functions"

# Redirects for vanillaLineBot
[[redirects]]
  from = "/callback/vanilla"
  to = "/.netlify/functions/vanillaLineBot"
  status = 200

# Redirects for dictLineBot
[[redirects]]
  from = "/callback/dict"
  to = "/.netlify/functions/dictLineBot"
  status = 200

# Redirects for toyPeopleLineBot
[[redirects]]
  from = "/callback/toyPeople"
  to = "/.netlify/functions/toyPeopleLineBot"
  status = 200
  
# Redirects for pokeBeachLineBot
[[redirects]]
  from = "/callback/pokeBeach"
  to = "/.netlify/functions/pokeBeachLineBot"
  status = 200
